root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.eslint.json'
  tsconfigRootDir: ./
extends: 
  - 'moon'
  - 'moon/node'
rules:
  'import/no-useless-path-segments': 'off'
  'import/no-unresolved': 'off'
